// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: srctree.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SrcTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   *string                `protobuf:"bytes,1,opt,name=PackageName" json:"PackageName,omitempty"`
	Imports       []*SrcTree             `protobuf:"bytes,2,rep,name=Imports" json:"Imports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SrcTree) Reset() {
	*x = SrcTree{}
	mi := &file_srctree_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SrcTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrcTree) ProtoMessage() {}

func (x *SrcTree) ProtoReflect() protoreflect.Message {
	mi := &file_srctree_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrcTree.ProtoReflect.Descriptor instead.
func (*SrcTree) Descriptor() ([]byte, []int) {
	return file_srctree_proto_rawDescGZIP(), []int{0}
}

func (x *SrcTree) GetPackageName() string {
	if x != nil && x.PackageName != nil {
		return *x.PackageName
	}
	return ""
}

func (x *SrcTree) GetImports() []*SrcTree {
	if x != nil {
		return x.Imports
	}
	return nil
}

var File_srctree_proto protoreflect.FileDescriptor

var file_srctree_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x72, 0x63, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x54, 0x0a, 0x07, 0x53, 0x72, 0x63, 0x54, 0x72, 0x65, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x72, 0x63, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x07, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x41, 0x5a, 0x3f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x74, 0x79, 0x64, 0x69,
	0x64, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x75, 0x69, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x6e,
}

var (
	file_srctree_proto_rawDescOnce sync.Once
	file_srctree_proto_rawDescData = file_srctree_proto_rawDesc
)

func file_srctree_proto_rawDescGZIP() []byte {
	file_srctree_proto_rawDescOnce.Do(func() {
		file_srctree_proto_rawDescData = protoimpl.X.CompressGZIP(file_srctree_proto_rawDescData)
	})
	return file_srctree_proto_rawDescData
}

var file_srctree_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_srctree_proto_goTypes = []any{
	(*SrcTree)(nil), // 0: main.SrcTree
}
var file_srctree_proto_depIdxs = []int32{
	0, // 0: main.SrcTree.Imports:type_name -> main.SrcTree
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_srctree_proto_init() }
func file_srctree_proto_init() {
	if File_srctree_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_srctree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_srctree_proto_goTypes,
		DependencyIndexes: file_srctree_proto_depIdxs,
		MessageInfos:      file_srctree_proto_msgTypes,
	}.Build()
	File_srctree_proto = out.File
	file_srctree_proto_rawDesc = nil
	file_srctree_proto_goTypes = nil
	file_srctree_proto_depIdxs = nil
}
