//  Copyright 2015 Walter Schulze
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: topsyturvy.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopsyTurvy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *Topsy                 `protobuf:"bytes,1,opt,name=Top" json:"Top,omitempty"`
	Turf          *Turvy                 `protobuf:"bytes,2,opt,name=Turf" json:"Turf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopsyTurvy) Reset() {
	*x = TopsyTurvy{}
	mi := &file_topsyturvy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopsyTurvy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopsyTurvy) ProtoMessage() {}

func (x *TopsyTurvy) ProtoReflect() protoreflect.Message {
	mi := &file_topsyturvy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopsyTurvy.ProtoReflect.Descriptor instead.
func (*TopsyTurvy) Descriptor() ([]byte, []int) {
	return file_topsyturvy_proto_rawDescGZIP(), []int{0}
}

func (x *TopsyTurvy) GetTop() *Topsy {
	if x != nil {
		return x.Top
	}
	return nil
}

func (x *TopsyTurvy) GetTurf() *Turvy {
	if x != nil {
		return x.Turf
	}
	return nil
}

type Topsy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *int64                 `protobuf:"varint,1,opt,name=Top" json:"Top,omitempty"`
	Turf          *int64                 `protobuf:"varint,2,opt,name=Turf" json:"Turf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topsy) Reset() {
	*x = Topsy{}
	mi := &file_topsyturvy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topsy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topsy) ProtoMessage() {}

func (x *Topsy) ProtoReflect() protoreflect.Message {
	mi := &file_topsyturvy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topsy.ProtoReflect.Descriptor instead.
func (*Topsy) Descriptor() ([]byte, []int) {
	return file_topsyturvy_proto_rawDescGZIP(), []int{1}
}

func (x *Topsy) GetTop() int64 {
	if x != nil && x.Top != nil {
		return *x.Top
	}
	return 0
}

func (x *Topsy) GetTurf() int64 {
	if x != nil && x.Turf != nil {
		return *x.Turf
	}
	return 0
}

type Turvy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turf          *int64                 `protobuf:"varint,1,opt,name=Turf" json:"Turf,omitempty"`
	Top           *int64                 `protobuf:"varint,2,opt,name=Top" json:"Top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turvy) Reset() {
	*x = Turvy{}
	mi := &file_topsyturvy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turvy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turvy) ProtoMessage() {}

func (x *Turvy) ProtoReflect() protoreflect.Message {
	mi := &file_topsyturvy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turvy.ProtoReflect.Descriptor instead.
func (*Turvy) Descriptor() ([]byte, []int) {
	return file_topsyturvy_proto_rawDescGZIP(), []int{2}
}

func (x *Turvy) GetTurf() int64 {
	if x != nil && x.Turf != nil {
		return *x.Turf
	}
	return 0
}

func (x *Turvy) GetTop() int64 {
	if x != nil && x.Top != nil {
		return *x.Top
	}
	return 0
}

var File_topsyturvy_proto protoreflect.FileDescriptor

var file_topsyturvy_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x6f, 0x70, 0x73, 0x79, 0x74, 0x75, 0x72, 0x76, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x4c, 0x0a, 0x0a, 0x54, 0x6f, 0x70, 0x73,
	0x79, 0x54, 0x75, 0x72, 0x76, 0x79, 0x12, 0x1d, 0x0a, 0x03, 0x54, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x6f, 0x70, 0x73, 0x79,
	0x52, 0x03, 0x54, 0x6f, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x54, 0x75, 0x72, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x75, 0x72, 0x76, 0x79,
	0x52, 0x04, 0x54, 0x75, 0x72, 0x66, 0x22, 0x2d, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x73, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x54, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x54, 0x6f,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x75, 0x72, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x54, 0x75, 0x72, 0x66, 0x22, 0x2d, 0x0a, 0x05, 0x54, 0x75, 0x72, 0x76, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x75, 0x72, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x75,
	0x72, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x54, 0x6f, 0x70, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x74, 0x79, 0x64, 0x69, 0x64, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x75, 0x69, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x67,
	0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2d, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x6e,
}

var (
	file_topsyturvy_proto_rawDescOnce sync.Once
	file_topsyturvy_proto_rawDescData = file_topsyturvy_proto_rawDesc
)

func file_topsyturvy_proto_rawDescGZIP() []byte {
	file_topsyturvy_proto_rawDescOnce.Do(func() {
		file_topsyturvy_proto_rawDescData = protoimpl.X.CompressGZIP(file_topsyturvy_proto_rawDescData)
	})
	return file_topsyturvy_proto_rawDescData
}

var file_topsyturvy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_topsyturvy_proto_goTypes = []any{
	(*TopsyTurvy)(nil), // 0: main.TopsyTurvy
	(*Topsy)(nil),      // 1: main.Topsy
	(*Turvy)(nil),      // 2: main.Turvy
}
var file_topsyturvy_proto_depIdxs = []int32{
	1, // 0: main.TopsyTurvy.Top:type_name -> main.Topsy
	2, // 1: main.TopsyTurvy.Turf:type_name -> main.Turvy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_topsyturvy_proto_init() }
func file_topsyturvy_proto_init() {
	if File_topsyturvy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topsyturvy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topsyturvy_proto_goTypes,
		DependencyIndexes: file_topsyturvy_proto_depIdxs,
		MessageInfos:      file_topsyturvy_proto_msgTypes,
	}.Build()
	File_topsyturvy_proto = out.File
	file_topsyturvy_proto_rawDesc = nil
	file_topsyturvy_proto_goTypes = nil
	file_topsyturvy_proto_depIdxs = nil
}
