name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/github.com/katydid/testsuite
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Fetch dependencies
      run: |
        cd gopath/github.com/katydid/testsuite
        go mod download -x
    - name: Install tools
      run: |
        cd gopath/github.com/katydid/testsuite
        go install -x google.golang.org/protobuf/cmd/protoc-gen-go
    - name: Setup protoc
      run: |
        cd gopath/github.com/katydid/testsuite
        ./install_protoc.sh
    - name: Protoc version
      run: |
        cd gopath/github.com/katydid/testsuite
        PATH=$HOME/bin:$PATH protoc --version
    - name: env
      run: env && go env && pwd
    - name: tree
      run: tree
    - name: Build
      run: |
        cd gopath/github.com/katydid/testsuite
        make build
    - name: Generate Tests
      run: |
        cd gopath/github.com/katydid/testsuite
        PATH=$HOME/bin:$PATH make regenerate-tests
